CREATE DATABASE BAITHI2
GO

USE BAITHI2
GO
SET DATEFORMAT DMY

--1
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(5) PRIMARY KEY,
	TENKH VARCHAR(50),
	DIACHI VARCHAR(30),
	LOAIKH VARCHAR(10),
)

CREATE TABLE THUOC
(
	MATHUOC VARCHAR(5) PRIMARY KEY,
	TENTHUOC VARCHAR(20),
	NGUOCGOC VARCHAR(30),
	GIA INT,
)

CREATE TABLE DONTHUOC
(
	MADT VARCHAR(5) PRIMARY KEY,
	NGDT DATE,
	MAKH VARCHAR(5),
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)
)

CREATE TABLE CTDT
(
	MADT VARCHAR(5),
	MATHUOC VARCHAR(5),
	SOLUONG INT,
	FOREIGN KEY (MADT) REFERENCES DONTHUOC (MADT),
	FOREIGN KEY (MATHUOC) REFERENCES THUOC (MATHUOC),
)

--2
INSERT INTO KHACHHANG VALUES ('KH001', 'Nguyen Trong Tan', 'Tp.HCM', 'VIP'),
							 ('KH002', 'Tran Tien Trien', 'Dong Nai', 'Thuong'),
							 ('KH003', 'Hoang My Uyen', 'Kien Giang', 'Thuong')

INSERT INTO THUOC VALUES ('MT001', 'Aspirin', 'Uc', 480000),
						 ('MT002', 'Panadol', 'Phap', 200000),
						 ('MT003', 'Vaccine', 'My', 140000)

INSERT INTO DONTHUOC VALUES ('00001', '12-11-2018', 'KH001'),
							('00002', '10-10-2018', 'KH003'),
							('00003', '10-12-2018', 'KH002')

INSERT INTO CTDT VALUES ('00001', 'MT001', 3),
					    ('00001', 'MT002', 8),
						('00003', 'MT003', 12)

--3
ALTER TABLE CTDT ADD CONSTRAINT CHK_SL CHECK (SOLUONG > 0)

--4
CREATE TRIGGER CHK_TRIG_GIATHUOC
ON THUOC FOR INSERT, UPDATE
AS
BEGIN
		DECLARE @GIA INT
		SELECT @GIA = GIA FROM INSERTED
		IF (@GIA < 1000)
			BEGIN
				PRINT N'Gia thuoc khong hop le'
				ROLLBACK TRANSACTION
			END
		ELSE 
			BEGIN
				PRINT N'Thong tin thuoc moi da duoc nhap thanh cong'
			END
END

--5
SELECT MAKH, TENKH
FROM KHACHHANG
WHERE DIACHI = 'Tp.HCM'

--6
SELECT *
FROM DONTHUOC
WHERE MONTH(NGDT) < 12 AND YEAR(NGDT) <= 2018

--7
SELECT TOP 1 KH.MAKH, KH.TENKH, SUM(CTDT.SOLUONG * THUOC.GIA) AS TONGGIATRIDONTHUOC
FROM KHACHHANG KH
JOIN DONTHUOC DT ON DT.MAKH = KH.MAKH
JOIN CTDT ON CTDT.MADT = DT.MADT
JOIN THUOC ON THUOC.MATHUOC = CTDT.MATHUOC
GROUP BY KH.MAKH, KH.TENKH
ORDER BY TONGGIATRIDONTHUOC DESC

--8
SELECT LOAIKH, SUM(CTDT.SOLUONG * THUOC.GIA) AS TONGGIATRI
FROM KHACHHANG KH
JOIN DONTHUOC DT ON DT.MAKH = KH.MAKH
JOIN CTDT ON CTDT.MADT = DT.MADT
JOIN THUOC ON THUOC.MATHUOC = CTDT.MATHUOC
WHERE LOAIKH = 'VIP'
GROUP BY LOAIKH

SELECT * FROM KHACHHANG
SELECT * FROM THUOC
SELECT * FROM DONTHUOC
SELECT * FROM CTDT

