--1
CREATE DATABASE DB_DE03
GO

USE DB_DE03
GO

SET DATEFORMAT DMY

CREATE TABLE KYTHI
(
	MAKT VARCHAR(5) PRIMARY KEY,
	NGBD SMALLDATETIME,
	NGKT SMALLDATETIME,
	NUOCTC VARCHAR(40),
)
CREATE TABLE THISINH
(
	MATS VARCHAR(5) PRIMARY KEY,
	TENTS VARCHAR(40),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	QUOCTICH VARCHAR(40),
)
CREATE TABLE BAITOAN
(
	MABT VARCHAR(5) PRIMARY KEY,
	MAKT VARCHAR(5),
	THUTU INT,
	DIEMTD INT,
	THELOAI VARCHAR(20),
)
CREATE TABLE KETQUA
(
	MAKT VARCHAR(5),
	MATS VARCHAR(5),
	MABT VARCHAR(5),
	DIEM INT,
)
ALTER TABLE KETQUA ADD CONSTRAINT FK_KT FOREIGN KEY (MAKT) REFERENCES KYTHI (MAKT)
ALTER TABLE KETQUA ADD CONSTRAINT FK_TS FOREIGN KEY (MATS) REFERENCES THISINH (MATS)

--2.
INSERT INTO KYTHI VALUES ('KT001', 12/07/2017, 23/07/2017, 'Brazil')
INSERT INTO KYTHI VALUES ('KT002', 03/07/2018, 14/07/2018, 'Romania')
INSERT INTO KYTHI VALUES ('KT003', 11/07/2019, 22/07/2019, 'United Kingdom')

INSERT INTO THISINH VALUES ('TS001', 'Nguyen Thuan Hung', 25/06/2001, 'Nam', 'Viet Nam')
INSERT INTO THISINH VALUES ('TS002', 'Xu Chen Tan', 16/05/2002, 'Nam', 'Singapore')
INSERT INTO THISINH VALUES ('TS003', 'Youngjun Cho', 26/06/2002, 'Nam', 'Republic of Korea')

INSERT INTO BAITOAN VALUES ('BT001', 'KT001', 1, 7, 'Dai so')
INSERT INTO BAITOAN VALUES ('BT002', 'KT001', 2, 7, 'To hop')
INSERT INTO BAITOAN VALUES ('BT003', 'KT001', 3, 7, 'Ly thuyet so')

INSERT INTO KETQUA VALUES ('KT001', 'TS001', 'BT001', 6)
INSERT INTO KETQUA VALUES ('KT001', 'TS001', 'BT002', 6)
INSERT INTO KETQUA VALUES ('KT001', 'TS002', 'BT001', 7)

SELECT * FROM KYTHI
SELECT * FROM THISINH
SELECT * FROM BAITOAN
SELECT * FROM KETQUA

--3
CREATE TRIGGER CHK_TRG_THUTU
ON BAITOAN FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @THUTU INT
	SELECT @THUTU = THUTU FROM INSERTED
	IF @THUTU < 1 OR @THUTU > 6
		BEGIN
		PRINT N'THU TU BAI TOAN PHAI LA CAC SO NGUYEN TU 1 DEN 6'
		END
END

--4
CREATE TRIGGER CHK_DIEMTS
ON KETQUA FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @DIEM INT
	DECLARE @MABT VARCHAR(5)
	SELECT @DIEM = DIEM, @MABT = MABT FROM INSERTED
	IF @DIEM > (
					SELECT DIEMTD
					FROM BAITOAN
					WHERE @MABT = MABT
				)
	BEGIN
		PRINT N'DIEM THI SINH DAT DUOC O MOI BAI TOAN KHONG DUOC QUA DIEM TOI DA CUA BAI TOAN DO'
	END
END

--5
SELECT TS.MATS, TS.TENTS
FROM THISINH TS
JOIN KETQUA KQ ON KQ.MATS = TS.MATS
JOIN BAITOAN BT ON BT.MABT = KQ.MABT
JOIN KYTHI KT ON KT.MAKT = KQ.MAKT AND KT.MAKT = BT.MAKT
WHERE YEAR(KT.NGBD) = 2018 AND BT.THUTU = 6 AND KQ.DIEM = BT.DIEMTD

--6
SELECT KQ.MABT
FROM KETQUA KQ
JOIN BAITOAN BT ON BT.MABT = KQ.MABT
JOIN KYTHI KT ON KT.MAKT = BT.MAKT

--7
SELECT BT.THELOAI
FROM BAITOAN BT
JOIN KETQUA KQ ON KQ.MABT = BT.MABT
GROUP BY BT.THELOAI
HAVING COUNT(KQ.MATS) = (
							SELECT TOP 1 COUNT(KQ2.MATS)
							FROM KETQUA KQ2
							JOIN BAITOAN BT2 ON BT2.MABT = KQ2.MABT
							WHERE BT2.DIEMTD = KQ2.DIEM
							GROUP BY BT2.THELOAI
							ORDER BY BT2.THELOAI DESC
						)

--8
SELECT *
FROM THISINH TS
WHERE MATS IN (
				SELECT KQ.MATS
				FROM KETQUA KQ
				JOIN KYTHI KT ON KT.MAKT = KQ.MAKT
				WHERE YEAR(KT.NGBD) = 2019 
				AND KQ.MABT IN (
									SELECT BT.MABT
									FROM BAITOAN BT
									JOIN KYTHI KT2 ON KT2.MAKT = BT.MAKT
									WHERE YEAR(KT.NGBD) = 2019
				))