CREATE DATABASE QLTV
USE QLTV

SET DATEFORMAT DMY

CREATE TABLE SACH
(
	MASACH CHAR(5) PRIMARY KEY,
	TENSACH NVARCHAR(100),
	THELOAI NVARCHAR(30),
	DONGIA MONEY,
	SOLUONG INT
)

CREATE TABLE TACGIA
(
	MATG CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	QUOCTICH NVARCHAR(30),
	NGAYSINH SMALLDATETIME,
	DIENTHOAI VARCHAR(15)
)

CREATE TABLE TACGIA_SACH
(
	MATG CHAR(5),
	MASACH CHAR(5),
	FOREIGN KEY (MATG) REFERENCES TACGIA(MATG),
	FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
	CONSTRAINT KHOA PRIMARY KEY (MATG, MASACH)
)

CREATE TABLE DOCGIA
(
	MADG CHAR(5) PRIMARY KEY,
	TENDG NVARCHAR(50),
	DIACHI NVARCHAR(50),
	NGAYSINH SMALLDATETIME,
	DIENTHOAI VARCHAR(15),
	NGDK SMALLDATETIME
)

CREATE TABLE PHATHANH
(
	MAPH CHAR(5) PRIMARY KEY,
	MASACH CHAR(5),
	NGAYPH SMALLDATETIME,
	SOLUONG INT,
	NXB NVARCHAR(100),
	LANPHATHANH INT,
	FOREIGN KEY (MASACH) REFERENCES SACH(MASACH) 
)

CREATE TABLE MUONSACH 
(
	MAMUON CHAR(5) PRIMARY KEY,
	MADG CHAR(5),
	MASACH CHAR(5),
	NGAYMUON SMALLDATETIME,
	NGAYTRA SMALLDATETIME,
	TRANGTHAI NVARCHAR(20),
	FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG),
	FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
)
GO

CREATE TRIGGER NGPH_NGSTG ON PHATHANH
AFTER UPDATE, INSERT
AS BEGIN
	DECLARE @NGPH SMALLDATETIME, @NGSTG SMALLDATETIME
	SELECT @NGPH = NGAYPH, @NGSTG = NGAYSINH
	FROM INSERTED AS I
	JOIN TACGIA_SACH TGS ON I.MASACH = TGS.MASACH
	JOIN TACGIA TG ON TGS.MATG = TG.MATG
	IF (UPDATE(NGAYPH)) BEGIN
		IF @NGPH < @NGSTG BEGIN
			PRINT('ERROR')
			ROLLBACK TRANSACTION
		END
	END
	IF @NGPH < @NGSTG BEGIN
		PRINT('ERROR')
		ROLLBACK TRANSACTION
	END
END
GO

ALTER TABLE PHATHANH 
ADD CONSTRAINT SLPH CHECK (SOLUONG >= 500)

SELECT MADG, TENDG
FROM DOCGIA
WHERE MADG IN (
	SELECT MADG
	FROM MUONSACH
	WHERE NGAYMUON = '10/12/2024')

SELECT DISTINCT TG.MATG, TG.HOTEN
FROM TACGIA TG
JOIN TACGIA_SACH TGS ON TG.MATG = TGS.MATG
JOIN SACH S ON S.MASACH = TGS.MASACH
JOIN PHATHANH PH ON S.MASACH = PH.MASACH
WHERE TENSACH = N'Cấu trúc rời rạc' AND NXB = 'ĐHQG-HCM'

SELECT TG.MATG, TG.HOTEN, COUNT(MASACH)
FROM TACGIA TG
JOIN TACGIA_SACH TGS ON TG.MATG = TGS.MATG
GROUP BY TG.MATG, TG.HOTEN
ORDER BY COUNT(MASACH) DESC

--NẾU BẢO TÌM THÔNG TIN VỀ BẢNG NÀO MÀ KHÔNG NÓI GÌ THÊM THÌ PHẢI CHO BIẾT HẾT MỌI THUỘC TÍNH TRONG BẢNG 
SELECT *
FROM DOCGIA DG
WHERE MADG IN(
	SELECT MADG
	FROM MUONSACH MS
	JOIN SACH S ON MS.MASACH = S.MASACH
	WHERE YEAR(NGAYMUON) = '2024'
	GROUP BY MADG
	HAVING COUNT(DISTINCT THELOAI) >= 3
)


SELECT NXB
FROM PHATHANH PH
LEFT JOIN MUONSACH MS ON PH.MASACH = PH.MASACH
WHERE MAMUON IS NULL
GROUP BY NXB
HAVING COUNT(DISTINCT PH.MASACH) > 5 

SELECT DG.MADG, DG.TENDG
FROM DOCGIA DG
WHERE MADG IN (
	SELECT MADG
	FROM MUONSACH MS
	JOIN SACH S ON MS.MASACH = S.MASACH
	WHERE MS.MADG = DG.MADG 
	AND THELOAI IN (N'Khoa học viễn tưởng', N'Kinh tế')
	AND YEAR(MS.NGAYMUON) = '2024'
	GROUP BY MADG
	HAVING COUNT(S.MASACH) = (
		SELECT COUNT(*)
		FROM SACH
		WHERE THELOAI IN (N'Khoa học viễn tưởng', N'Kinh tế')
		)
	)






