USE MASTER 
GO
ALTER DATABASE HK1_04 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE HK1_04
-------------------------------------



CREATE DATABASE HK1_04


USE HK1_04
SET DATEFORMAT DMY

--1
CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) PRIMARY KEY,
	TENKH VARCHAR(40),
	DIACHI VARCHAR(100),
	LOAIKH VARCHAR(40)
)

CREATE TABLE LOAICAY
(
	MALC CHAR(4) PRIMARY KEY,
	TENLC VARCHAR(40),
	XUATXU VARCHAR(40),
	GIA MONEY
)

CREATE TABLE HOADON
(
	SOHD CHAR(5) PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	KHUYENMAI INT
)

CREATE TABLE CTHD
(
	SOHD CHAR(5),
	MALC CHAR(4),
	SOLUONG SMALLINT,
	CONSTRAINT CTHD_KEY PRIMARY KEY (SOHD, MALC)
)
--------------------------------------------------
ALTER TABLE HOADON ADD CONSTRAINT MAKH
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE CTHD ADD CONSTRAINT SOHD
FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)

ALTER TABLE CTHD ADD CONSTRAINT MALC
FOREIGN KEY (MALC) REFERENCES LOAICAY(MALC)

--2
INSERT INTO KHACHHANG VALUES
('KH01', 'LIZ KIM CUONG', 'HA NOI', 'VANG LAI'),
('KH02', 'IVONE DIEU LINH', 'DA NANG', 'THUONG XUYEN'),
('KH03', 'EMMA NHAT KHANH', 'TP.HCM', 'VANG LAI')
SELECT * FROM KHACHHANG

INSERT INTO LOAICAY VALUES
('LC01', 'XUONG RONG TAI THO', 'MEXICO', 180000),
('LC02', 'SEN THACH NGOC', 'ANH', 300000),
('LC03', 'BA MAU RAU', 'NAM PHI', 270000)
SELECT * FROM LOAICAY

INSERT INTO HOADON VALUES
('00001', '22/11/2017', 'KH01', 5),
('00002', '4/12/2017', 'KH03', 5),
('00003', '10/12/2017', 'KH02', 10)
SELECT * FROM HOADON

INSERT INTO CTHD VALUES
('00001', 'LC01', 1),
('00001', 'LC02', 2),
('00003', 'LC03', 5)
SELECT * FROM CTHD

--3
GO
CREATE TRIGGER GIACA_ANH ON LOAICAY
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @GIA MONEY, @XUATXU VARCHAR(40)
	SELECT @GIA = I.GIA, @XUATXU = I.XUATXU
	FROM INSERTED I
	IF (@XUATXU = 'ANH') BEGIN
		IF(@GIA < 250000) BEGIN
			PRINT('GIA THAP HON TIEU CHUAN ANH!')
			ROLLBACK TRANSACTION
		END
	END

END

--4
GO
CREATE TRIGGER GIAMGIA10 ON HOADON
AFTER INSERT, UPDATE
AS BEGIN 
	DECLARE @SOLUONG INT, @SOHD CHAR(5)
	SELECT @SOLUONG = SUM(CTHD.SOLUONG), @SOHD = I.SOHD
	FROM INSERTED I
	JOIN CTHD ON I.SOHD = CTHD.SOHD
	IF (@SOLUONG >= 5) BEGIN
		PRINT('DU DK GIAM GIA 10')
		UPDATE HOADON
		SET KHUYENMAI = 10
		WHERE SOHD = @SOHD
	END
END

--5
SELECT *
FROM HOADON
WHERE YEAR(NGHD) = 2017 AND MONTH(NGHD) >= 9
ORDER BY KHUYENMAI ASC

--6
SELECT * 
FROM LOAICAY
WHERE MALC IN (
	SELECT TOP 1 CTHD.MALC
	FROM CTHD
	JOIN HOADON HD ON CTHD.SOHD = HD.SOHD
	WHERE MONTH(HD.NGHD) = 12
	GROUP BY CTHD.MALC
	ORDER BY SUM(CTHD.SOLUONG) ASC
)

--7
SELECT * 
FROM LOAICAY
WHERE MALC IN (
	SELECT MALC
	FROM CTHD CT
	JOIN HOADON HD ON CT.SOHD = HD.SOHD
	JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
	WHERE KH.LOAIKH = 'THUONG XUYEN'
	INTERSECT
	SELECT MALC
	FROM CTHD CT
	JOIN HOADON HD ON CT.SOHD = HD.SOHD
	JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
	WHERE KH.LOAIKH = 'VANG LAI'
)

--8
SELECT *
FROM KHACHHANG
WHERE MAKH IN (
	SELECT MAKH
	FROM HOADON HD
	JOIN CTHD CT ON HD.SOHD = CT.SOHD
	GROUP BY HD.MAKH
	HAVING COUNT(DISTINCT CT.MALC) = (
		SELECT COUNT(*)
		FROM LOAICAY
		)
)









